#!/bin/sh -e

# Go in the app directory.
cd "$(dirname "$0")/"

for app in . api chat gpio web electron; do
    (
        cd "$app"
        npm install

        if [ -f config.json.dist ] && ! [ -f config.json ]; then
            cp config.json.dist config.json
        fi
    )
done
