#!/bin/sh -e

# Go in the app directory.
cd "$(dirname "$0")/"

for app in . api chat gpio screen web; do
    (
        cd "$app"

        if [ -f config.json.dist ] && ! [ -f config.json ]; then
            cp config.json.dist config.json
        fi

        npm install
    )
done
