#!/bin/sh -e

# Go in the app directory.
cd "$(dirname "$0")"

# Kill running background jobs on exit <https://stackoverflow.com/a/22644006>.
trap 'exit' INT TERM
trap 'kill 0' EXIT

# Run backend with restart loop on crash.
run() {
    while npm start | tee -a pongdome.log || true; do
        echo "restarting in 5 seconds"
        sleep 5
    done
}


# Removes cursor from screen when app is running.
unclutter -idle 0.1 -root &

# Run backend.
run &

# Run frontend.
DISPLAY=:0 chromium-browser --kiosk --disable-session-crashed-bubble --disable-infobars "web/index.html" &

# Wait for background processes.
wait
